// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbbskhkrqqkjeiuttojy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiYnNraGtycXFramVpdXR0b2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwODE4NTEsImV4cCI6MjA3NTY1Nzg1MX0.jPCbxLQQE3S4q53e5QZ4FBTJHc8lDMlf8Tdam8dyb48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});